#!/bin/bash

BRIGHTNESS=`cat /sys/class/backlight/intel_backlight/brightness`
MAX_BRIGHTNESS=`cat /sys/class/backlight/intel_backlight/max_brightness`
PERCENT=$(( ($BRIGHTNESS * 100) / $MAX_BRIGHTNESS))
echo -e "\\u2600: $PERCENT%"

