#! /bin/bash

# $MUTE is the 'n' of "on" if the sound is muted, the 'f' of "off" if not
MUTE=`amixer -c0 get Master | tail -c 3`
if [ "$MUTE" == "f]" ]; then
       COLOUR="red"
else
       COLOUR="green"
fi

# Returns the current master volume; requires alsa-utils
VALUE=`amixer -c0 get Master | sed s/%.*$// | sed 's/^.*\[//' | tail -n 1`

# Format and print
echo "<fc=$COLOUR>$VALUE</fc>%"

